version: 0.0
os: linux
files:
  - source: dist/
    destination: /opt/bucketbuddy/dist
    overwrite: yes
  - source: server/
    destination: /opt/bucketbuddy/server
    overwrite: yes
  - source: scripts/
    destination: /opt/bucketbuddy/scripts
    overwrite: yes
  - source: shared/
    destination: /opt/bucketbuddy/shared
    overwrite: yes
  - source: ecosystem.config.js
    destination: /opt/bucketbuddy
    overwrite: yes
  - source: package.json
    destination: /opt/bucketbuddy
    overwrite: yes
  - source: package-lock.json
    destination: /opt/bucketbuddy
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user
