version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing global dependencies...
      - npm install -g pm2
      - echo Installing project dependencies from root...
      - npm ci
      - echo Checking Node.js and npm versions
      - node --version
      - npm --version

  build:
    commands:
      - echo Building the application...
      - npm run build
      - echo Build completed successfully
      - echo Checking dist directory...
      - ls -la dist/

  post_build:
    commands:
      - echo Build phase completed
      - echo Preparing deployment artifacts...
      - ls -la

artifacts:
  files:
    - dist/**/*
    - server/**/*
    - scripts/**/*
    - shared/**/*
    - appspec.yml
    - ecosystem.config.js
    - package.json
    - package-lock.json
  exclude-paths:
    - node_modules/**/*
    - .git/**/*
    - "*.md"
    - "terraform/**/*"
    - "client/**/*"
    - ".env*"
    - "coverage/**/*"
    - "test/**/*"
    - "tests/**/*"
    - "*.test.js"
    - "*.spec.js"

cache:
  paths:
    - node_modules/**/*
